line_length: 200
function_parameter_count: 10

disabled_rules:
 - trailing_whitespace
 - identifier_name
 - type_name
 - force_try


excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods


